# Generated by Django 4.2.11 on 2024-04-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Sapp',
        ),
    ]
